[features]
seeds = false
skip-lint = false

[programs.localnet]
test_contract = "4cRuEdrN1psiLR9kejes449yGJTrKfM4XfRW2EMxhKtf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
